
name: pm2-restart

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
jobs:
  pm2-restart-workflow:
    runs-on: self-hosted
    steps:
      - name: restart-pm2
        run: pm2 restart flask-app
      - name: echo-on-ec2
        run: echo "Hello WORLD  "
