
name: CI CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
jobs:
  pm2-restart-workflow:
    runs-on: self-hosted
    steps:
      - name: moving to working directory
        run: cd /var/www/vlad12345
      - name: checking git repository
        run: ls -lart

      - name: clone changes
        run: git pull
